import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "@/ui/globals.css"
import Sidebar from "@/ui/sidebar/SideBar"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={`${inter.className} antialiased flex dark:bg-bg-dark dark:text-text-dark`}>
                <div className="dark:bg-bg-soft-dark flex-[1] p-5">
                    <Sidebar />
                </div>
                <div className="flex-[4] p-5">
                    {/* <Navbar /> */}
                    {children}
                </div>
            </body>
        </html>
    )
}
